config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'

  resources :departments do
    resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :update, :edit, :destroy]
  
  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
  end

  def edit
  end

  def create
    @department = Department.new(department_params)
    
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private
    def set_department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_department
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = @department.products
  end

  def show
  end

  def new
    @product = @department.products.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def create
    @product = @department.products.new(product_params)

    if @product.save
      redirect_to [@department, @product]
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to [@department, @product]
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to department_products_path
  end

  private
    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/departments/_form.html.erb
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departments/edit.html.erb
<h1>Edit <%= @department.name %></h1>
<%= render 'form' %>

app/views/departments/index.html.erb
<h1>Click a Department to View Products</h1>
<%= link_to 'Create a New Department', new_department_path %>
<ul>
  <% @departments.each do |department| %>
    <li><%= link_to department.name, department %></li>
  <% end %>
</ul>

app/views/departments/new.html.erb
<h1>Create New Department</h1>
<%= render 'form' %>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Products', department_products_path(@department) %>
<br />
<%= link_to 'Edit', edit_department_path(@department) %>
<br />
<%= link_to 'Delete', @department, method: :delete %>
<br />
<%= link_to 'Back', departments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for [@department, @product] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <br />
  <%= f.label :price %>
  <%= f.text_field :price, required: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1><%= @department.name %> Products</h1>
<%= link_to 'Create a new product', new_department_product_path(@department) %>
<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, [@department, product] %></li>
  <% end %>
  <li><%= link_to 'Back', department_path(@department) %></li>
</ul>

app/views/products/new.html.erb
<h1>Products#new</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @department.name %> - <%= @product.name %></h1>
<p>$<%= @product.price %></p>
<p><%= @product.body %></p>
<%= link_to 'Edit Product', edit_department_product_path([@department, @product]) %>
<%= link_to 'Delete Product', [@department, @product], method: :delete %>
<%= link_to 'Back', department_products_path(@department) %>